name: 2ยบ DS - Testes de POO - 4ยบ Bimestre

on:
  push:
  workflow_dispatch:

jobs:
  ex01-ola-mundo:
    name: ex01-npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/poo/ex01-npm
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex02-calculadora-organizada:
    name: ex02-calculadora-organizada
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/poo/ex02-calculadora-organizada
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test
