name: Exercícios 4º bimestre - 2º ANO

on:
  push:
  workflow_dispatch:

jobs:
  ex01-exercicio-exemplo:
    name: ex01-exercicio-exemplo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/poo/ex01-exercicio-exemplo
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test